name: 'anthms test action file'
description: 'Test composite action'

branding:
  icon: 'award'
  color: 'green'

runs:
  using: "composite"
  steps:
    - name: Echo something
      run: echo "something"
      shell: bash
